services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - FLASK_APP=rest.py
      - FLASK_RUN_HOST=0.0.0.0

volumes:
  db_data:
